/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:243e40ad-9a40-4002-b563-4fcab9ffc37a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vcqXSqWTg",
    "aws_user_pools_web_client_id": "7q1aj00vplqo07l7v59ohl4jm9",
    "oauth": {}
};


export default awsmobile;
